Implemented: logger using vue logger plugin(#103)
hotwax/user-management pull request #104
Opened 2024-02-16 11:36 UTC by Ritika-Patel08

### Related Issues

#103 

### Short Description and Why It's Useful

Added vue-logger-plugin dependency and use logger instead of console for errors.

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

2024-02-19 13:29 UTC, amansinghbais commented on src/main.ts
> -
Remove Unwanted changes

2024-02-19 13:29 UTC, amansinghbais commented on src/registerServiceWorker.ts
> -
Remove Unwanted changes

2024-03-20 05:49 UTC, ymaheshwari1 requested changes
Update the PR with main branch and check once again for all components.

2024-03-20 06:17 UTC, ymaheshwari1 requested changes

2024-03-20 06:17 UTC, ymaheshwari1 commented on src/registerServiceWorker.ts
> +import { register } from 'register-service-worker'
Remove this file and its import.

2024-03-20 07:32 UTC, ymaheshwari1 requested changes

2024-03-20 07:32 UTC, ymaheshwari1 commented on src/store/modules/util/actions.ts
> +import { UserService } from '@/services/UserService'
Unused import

2024-03-20 07:32 UTC, ymaheshwari1 commented on src/views/CreateUser.vue
> -        }
We need to keep this changes.

2024-03-20 10:35 UTC, Ritika-Patel08 commented on src/store/modules/util/actions.ts
> +import { UserService } from '@/services/UserService'
Removed this import.

2024-03-20 10:35 UTC, Ritika-Patel08 commented on src/views/CreateUser.vue
> -        }
Reverted. 
You can review.

2024-03-21 04:03 UTC, ymaheshwari1 requested changes

2024-03-21 04:03 UTC, ymaheshwari1 commented on src/store/modules/user/actions.ts
> -      return Promise.reject(err instanceof Object ? err :new Error((err)))
We need to keep this change as well.

2024-03-21 04:51 UTC, ymaheshwari1 approved these changes

2024-03-21 04:52 UTC, merged